### ISSUE TITLE
Pull to Windows: fatal: cannot create directory with name .../11. Prefix "test"': Invalid argument

### ISSUE THREAD

**Issue by madmarks** [TelerikAcademy/CSharp-Part-2#8]
I am trying to create a clone of this repo and I am on a Windows machine, but when I pull the TelerikAcademy/CSharp-Part-2 master branch to my local repo I get the error:

"fatal: cannot create directory at 'Topics/08. Text-Files/homework/11. Prefix "test"': Invalid argument".

I haven't found a solution; anyone encounter this before or have a solution? (Other than buying Mac)

**Comment by cuklev** [comment]
NTFS doesn't support quotes and some other symbols in filenames. The solutions are OS X, GNU/Linux, Bsd, ... and ofcourse b1f9941eb1160c33e3437ca00e7de4379fafd96a. You should be able to clone the repo and checkout the last commit now.
